### ISSUE TITLE
Les accents sont enlevés par irc

### ISSUE THREAD

**Issue by ghost** [MinetestForFun/irc_modpack#2]
Dans le fichier https://github.com/MinetestForFun/irc_modpack/blob/master/irc/hooks.lua#L22 il y a une fonction qui enlève les lettres/signes codés de 127 à 255, d'ou le problème d'accent qui ne s'affichent pas dans mt.

Je ne sais pas si on peut l'enlever sans avoir de soucis.
Peut être trouver les codes correspondants au lettres que l'on utilise le + "éèàç" par exemple et les ignorer en laissant le reste?

**Comment by ObaniGemini** [comment]
Pas bien difficile dit comme ça semble-t-il
http://www.asciitable.com/
é : 130
è : 138
à : 133
ç : 135

Ça à l'air simple à mettre en place, mais bonne chance s'il y a des bugs :p

**Comment by ghost** [comment]
Bon je n'y arrive pas, les caractères sont 160,167,168,169,170, sauf que le 195 fait partie du caractère et qu'il est enlevé, donc <invalide multibyte string> par ce que au lieu d'avoir "195+160" pour avoir la lettre, il reste que "160".

Si on laisse le 195 on a une erreur aussi vu qu'on enlève les autres lettres qui ont le 195 qui le compose.

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> print(string.byte("é"))
195
> print(string.byte("à"))
195
> print(string.byte("é", 2))
169
> print(string.byte("à", 2))
160
```
